### ISSUE TITLE
remove master branch 

### ISSUE THREAD

**Issue by janfb** [cne-tum/msne-datascience-2018-internal#23]
we should remove or rename the remote master branch because it is not the default branch anymore and because the its content is not in msne-datascience-2018:master. 

@mohammadbashiri do you agree?

**Comment by mohammadbashiri** [comment]
Yes, agreed. So if I understand correctly, the default branch for the private repo would be dev branch. And for the public one will still be master.
In summary:
- Changes to the private one must always be push to the dev branch (i.e., git push private dev_change_mb)
- Change to the public repo would be pushed to the master branch (i.e., git push origin master)

Is that right?

**Comment by janfb** [comment]
Correct. Done.
